version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d/
      - ./:/demp/
    links:
      - php
    networks:
      - demp

  php:
    image: php:fpm-alpine
    volumes:
      - ./:/demp/
    links:
      - "mysql"
    networks:
      - demp

  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    networks:
      - demp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    links:
      - "mysql:db"
    networks:
      - demp

networks:
  demp:
    driver: bridge