version: '3.7'

services:
  web:
    image: nginx:stable-alpine
    ports:
      - 8000:80
    volumes:
      - ./app:/app
      # - ./config/nginx/site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - php

  php:
    image: php:fpm-alpine
    volumes:
      - ./app:/app
      # - ./config/php/php.ini:/usr/local/etc/php/php.ini
