version: '3.7'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8000:80
    volumes:
      - ./app:/app
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - php

  php:
    image: php:fpm-alpine
    volumes:
      - ./app:/app
